import React, { createContext, useContext } from 'react';

const dictionary: { [key: string]: string } = {
    'nav.home': 'Home',
    'nav.shop': 'Shop',
    'nav.cart': 'Cart',
    'nav.allProducts': 'All Products',
    'common.search': 'Search',
    'common.profile': 'Profile',
    'category.title': 'What are you shopping for today?',
    'category.subtitle': 'Select a category to explore our curated collection',
    'category.yoga': 'Yoga',
    'category.yoga.desc': 'Find your zen with our premium yoga collection',
    'category.jogging': 'Jogging + Running + Walking',
    'category.jogging.desc': 'Gear designed for comfort and performance on every run',
    'category.gym': 'Gym',
    'category.gym.desc': 'Power your workouts with our gym essentials',
    'cart.title': 'Your Cart',
    'cart.empty.title': 'Your Cart is Empty',
    'cart.empty.desc': "Looks like you haven't added any items to your cart yet.",
    'cart.startShopping': 'Start Shopping',
    'cart.items': 'items in your cart',
    'cart.size': 'Size',
    'cart.color': 'Color',
    'cart.remove': 'Remove',
    'cart.summary': 'Order Summary',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Shipping',
    'cart.shipping.free': 'Free',
    'cart.tax': 'Estimated Tax',
    'cart.total': 'Total',
    'cart.checkout': 'Proceed to Checkout',
    'cart.continue': 'Continue Shopping',
    'cart.note.shipping': 'Free shipping on orders over $50.',
    'cart.note.taxes': 'Taxes calculated at checkout.',
    // Sort & Filters
    'sort.priceAsc': 'Price: Low to High',
    'sort.priceDesc': 'Price: High to Low',
    'sort.newest': 'Newest',
    'sort.rating': 'Rating',
    'sort.placeholder': 'Sort by',
    'listing.products': 'Products',
    'listing.filters': 'Filters',
    'listing.clearAll': 'Clear All',
    'listing.apply': 'Apply Filters',
    'listing.available': 'products available',
    'listing.noProducts': 'No products found',
    'listing.tryAdjusting': 'Try adjusting your filters or search term',
    'listing.new': 'New',
    'listing.bestSeller': 'Best Seller',
    'listing.searchPlaceholder': 'Search products...',
    'filter.price': 'Price Range',
    'filter.gender': 'Gender',
    'filter.categories': 'Categories',
    'filter.brands': 'Brands',
    'filter.colors': 'Colors',
    'filter.sizes': 'Sizes',
    // Product Detail
    'product.reviews': 'reviews',
    'product.description': 'Description',
    'product.size': 'Size',
    'product.quantity': 'Quantity',
    'product.addToCart': 'Add to Cart',
    'product.selectSize': 'Please select a size',
    'product.selectSizeDesc': 'You need to select a size before adding to cart',
    'product.added': 'Added to cart',
    'product.viewCart': 'View Cart',
    'product.notFound': 'Product not found',
    'product.back': 'Back to Products',
    // Payment
    'payment.title': 'Checkout',
    'payment.subtitle': 'Complete your purchase',
    'payment.shippingInfo': 'Shipping Information',
    'payment.name': 'Name',
    'payment.email': 'Email Address',
    'payment.address': 'Complete Address',
    'payment.phone': 'Phone Number',
    'payment.saveInfo': 'Save this information for next time',
    'payment.method': 'Payment Method',
    'payment.card': 'Card',
    'payment.cardName': 'Name on Card',
    'payment.cardNumber': 'Card Number',
    'payment.expiry': 'Expiry Date',
    'payment.cvv': 'CVV',
    'payment.saveCard': 'Save card for future purchases',
    'payment.complete': 'Complete Purchase',
    'payment.processing': 'Processing...',
    'payment.payWith': 'Pay with',
    'payment.error.validate': 'Validation Error',
    'payment.error.fill': 'Please fill in all required fields accurately.',
    'voice.start': 'Start Voice Assistant',
    'voice.end': 'End Voice Session',
    // Confirmation
    'confirm.title': 'Your order is confirmed!',
    'confirm.subtitle': "Thank you for your purchase. We've received your order and will begin processing it right away.",
    'confirm.orderInfo': 'Order Information',
    'confirm.orderNum': 'Order Number',
    'confirm.date': 'Date',
    'confirm.email': 'Email',
    'confirm.paymentMethod': 'Payment Method',
    'confirm.paymentDetails': 'Payment Details',
    'confirm.shippingAddress': 'Shipping Address',
    'confirm.notProvided': 'Not provided',
    'confirm.notSpecified': 'Not specified',
    'confirm.addressNotProvided': 'Address not provided',
    'confirm.creditCard': 'Credit Card',
    'confirm.cardEnding': 'Card ending in',
    'confirm.nameOnCard': 'Name on card',
    'confirm.emailNote': 'You will receive a confirmation email with your order details and tracking information once your order ships.',
    'confirm.backHome': 'Back to Home',
    // Filters - SubCategories
    'subcategory.equipment': 'Equipment',
    'subcategory.bottoms': 'Bottoms',
    'subcategory.tops': 'Tops',
    'subcategory.footwear': 'Footwear',
    'subcategory.outerwear': 'Outerwear',
    'subcategory.accessories': 'Accessories',
    // Filters - Colors
    'color.purple': 'Purple',
    'color.blue': 'Blue',
    'color.black': 'Black',
    'color.teal': 'Teal',
    'color.navy': 'Navy',
    'color.maroon': 'Maroon',
    'color.olive': 'Olive',
    'color.white': 'White',
    'color.blush': 'Blush',
    'color.sage': 'Sage',
    'color.gray': 'Gray',
    'color.grey': 'Gray',
    'color.red': 'Red',
    'color.orange': 'Orange',
    'color.pink': 'Pink',
    'color.silver': 'Silver',
    'color.green': 'Green',
    'color.peach': 'Peach',
    'color.khaki': 'Khaki',
    'color.natural cork': 'Natural Cork',
    'color.black/red': 'Black/Red',
    'color.black/blue': 'Black/Blue',
    'color.black/white': 'Black/White',
    'color.gray/blue': 'Gray/Blue',
    'color.navy/orange': 'Navy/Orange',
    'color.dark green': 'Dark Green',
    'color.light pink': 'Light Pink',
    'color.light grey': 'Light Gray',
    'color.light blue': 'Light Blue',
    'color.dark blue': 'Dark Blue',
    'color.dark grey': 'Dark Gray',
    // Filters - Materials
    'material.tpe': 'TPE',
    'material.eco-friendly': 'Eco-friendly',
    'material.nylon': 'Nylon',
    'material.spandex': 'Spandex',
    'material.modal': 'Modal',
    'material.cotton': 'Cotton',
    'material.mesh': 'Mesh',
    'material.rubber': 'Rubber',
    'material.polyester': 'Polyester',
    'material.elastane': 'Elastane',
    'material.leather': 'Leather',
    'material.neoprene': 'Neoprene',
    'material.cork': 'Cork',
    'material.fleece': 'Fleece',
    'material.jersey': 'Jersey',
    'material.breathable polyester': 'Breathable Polyester',
    'material.stretch fabric': 'Stretch Fabric',
    'material.compression fabric': 'Compression Fabric',
    'material.recycled polyester': 'Recycled Polyester',
    'material.water-resistant nylon': 'Water-resistant Nylon',
    // Filters - Genders
    'gender.men': 'Men',
    'gender.women': 'Women',
    'gender.unisex': 'Unisex',
    // Intro
    'intro.title': 'VOIX NOVA',
    'intro.subtitle': 'AI Shopping Assistant',
    'intro.description': 'Your personal AI-powered shopping companion that helps you find the perfect fitness gear with voice commands.',
    'intro.active': 'Active',
    'intro.greeting': '"Hi there! I\'m Voix Nova, your personal shopping assistant."',
    'intro.feature.voice': 'Voice Shopping',
    'intro.feature.voiceDesc': 'Find products using natural voice commands',
    'intro.feature.recommend': 'Smart Recommendations',
    'intro.feature.recommendDesc': 'Get personalized product suggestions',
    'intro.feature.seamless': 'Seamless Experience',
    'intro.feature.seamlessDesc': 'Shop hands-free from browsing to checkout',
    'intro.getStarted': 'Get Started',
    'intro.footer': 'Use the voice assistant at the bottom left to navigate by voice',
    // Not Found
    'notfound.title': '404',
    'notfound.subtitle': 'Oops! Page not found',
    'notfound.home': 'Return to Home',
};

interface LanguageContextType {
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const t = (key: string): string => {
        return dictionary[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
